# vim:fileencoding=utf-8:foldmethod=marker

# https://sw.kovidgoyal.net/kitty/conf/

# BEGIN_KITTY_THEME
# CLRS
include current-theme.conf
# END_KITTY_THEME

enable_audio_bell no

# Ring a bell when a command takes more than 10 seconds in a unfocused window
notify_on_cmd_finish unfocused 10.0 bell

# Max 75 FPS
repaint_delay 13

scrollback_lines 1000000
scrollback_pager_history_size 200

# Scrollback pager Ctrl+Shift+H mouse scroll support
scrollback_pager less --mouse --wheel-lines=5 -R +G

wheel_scroll_multiplier 10.0
touch_scroll_multiplier 5.0

# Avoid annoying trailing whitespace when copying from Pi
strip_trailing_spaces smart

map --allow-fallback=shifted,ascii ctrl+shift+v paste_from_clipboard
map --allow-fallback=shifted,ascii ctrl+shift+alt+v paste_from_selection

map ctrl+shift+o launch --location=hsplit --bias=50
map ctrl+shift+alt+o launch --location=vsplit --bias=50

# Cycle windows (panes) with Ctrl+Tab.
map ctrl+tab next_window
map ctrl+shift+tab previous_window

# Switch tabs with Alt+<num> (browser-style).
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
map alt+0 goto_tab -1

# Open links only with Ctrl+left click.
mouse_map left click ungrabbed mouse_handle_click selection prompt
mouse_map ctrl+left release grabbed,ungrabbed mouse_handle_click link
mouse_map ctrl+left press grabbed discard_event

cursor_shape block
enabled_layouts splits
